import bcrypt from "bcryptjs";

export default {
  users: [
    {
      name: "Basir",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Men's Classic T Shirt",
      slug: "Men's-Classic-T-Shirt",
      category: "Shirts",
      image: "/images/T-Shirt.jpg",
      price: 15,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      numReviews: 12,
      description: "high quality shirt",
    },
    {
      name: "Men's Polo Shirt",
      slug: "Men's-Polo-Shirt",
      category: "Shirts",
      image: "/images/Polo-shirt.jpg",
      price: 30,
      countInStock: 0,
      brand: "Nike",
      rating: 4.4,
      numReviews: 14,
      description: "high quality shirt",
    },
    {
      name: "Men's Dress Shirt",
      slug: "Men's-Dress-Shirt",
      category: "Shirts",
      image: "/images/Dress-shirt.jpg",
      price: 35,
      countInStock: 10,
      brand: "Nike",
      rating: 4.4,
      numReviews: 20,
      description: "high quality shirt",
    },
    {
      name: "Women's Summer Blouse",
      slug: "Women's-Summer-Blouse",
      category: "Blouses",
      image: "/images/Summer-blouse.jpg",
      price: 25,
      countInStock: 10,
      brand: "Nike",
      rating: 3.9,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Women's V-neck shirt",
      slug: "Women's-V-neck-shirt",
      category: "Shirts",
      image: "/images/V-neck-shirt.jpg",
      price: 20,
      countInStock: 10,
      brand: "Nike",
      rating: 4.4,
      numReviews: 18,
      description: "high quality shirt",
    },
    {
      name: "Women's Flannel",
      slug: "Women's-Flannel",
      category: "Shirts",
      image: "/images/Flannel.jpg",
      price: 30,
      countInStock: 10,
      brand: "Nike",
      rating: 4.7,
      numReviews: 8,
      description: "high quality shirt",
    },
    {
      name: "Men's Tank Top",
      slug: "Men's-Tank-Top",
      category: "Tank Tops",
      image: "/images/Tank.jpg",
      price: 25,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      numReviews: 14,
      description: "high quality shirt",
    },
    {
      name: "Women's Tank Top",
      slug: "Women's-Tank-Top",
      category: "Tank Tops",
      image: "/images/WTank.jpg",
      price: 25,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Men's Pullover Crewneck",
      slug: "Men's-Pullover-Crewneck",
      category: "Sweaters",
      image: "/images/Crewneck.jpg",
      price: 45,
      countInStock: 10,
      brand: "Nike",
      rating: 4.4,
      numReviews: 7,
      description: "high quality shirt",
    },
    {
      name: "Men's Athletic Hoodie",
      slug: "Men's-Athletic-Hoodie",
      category: "Sweaters",
      image: "/images/Hoodie.jpg",
      price: 40,
      countInStock: 10,
      brand: "Nike",
      rating: 4.8,
      numReviews: 19,
      description: "high quality shirt",
    },
    {
      name: "Women's Comfy Crewneck",
      slug: "Women's-Comfy-Crewneck",
      category: "Sweaters",
      image: "/images/WCrewneck.jpg",
      price: 35,
      countInStock: 10,
      brand: "Nike",
      rating: 3.9,
      numReviews: 19,
      description: "high quality shirt",
    },
    {
      name: "Women's Fleece Hoodie",
      slug: "Women's-Fleece-Hoodie",
      category: "Sweaters",
      image: "/images/WHoodie.jpg",
      price: 45,
      countInStock: 10,
      brand: "Nike",
      rating: 4.8,
      numReviews: 16,
      description: "high quality shirt",
    },
  ],
};
